### ISSUE TITLE
Unzip Test zip data failed

### ISSUE THREAD

**Issue by chengrongliang** [TencentYoutuResearch/ActionDetection-AFSD#1]
Hi Chuming, nice work, but when I unzip [TH14_Test_set_mp4.zip](https://storage.googleapis.com/thumos14_files/TH14_Test_set_mp4.zip) file, the password required?

**Comment by linchuming** [comment]
Hi, the password of this zip is "THUMOS14_REGISTERED" from the THUMOS14 website. I will add this password to our README. Thanks~
