### ISSUE TITLE
No such file or directory: 'cuhk-val/cuhk_val_simp_share.json'

### ISSUE THREAD

**Issue by chensiyao12** [TencentYoutuResearch/ActionDetection-AFSD#10]
Thank you very much for your work！
When I run AFSD/anet/test.py file,I met this problem.
Hope to get your answer！

**Comment by linchuming** [comment]
@chensiyao12 Thanks for your attention. You can get the download link from the inference section in AFSD/anet/README.md.

**Comment by chensiyao12** [comment]
@linchuming Thank you very much.

**Comment by chensiyao12** [comment]
@linchuming I would like to use my own data set to train the model. How can I get the class score of my own data in the test？

**Comment by linchuming** [comment]
@chensiyao12 If you need to predict class score, you can refer the model design for THUMOS14 dataset. For ActivityNet dataset, we refer previous work, such as BMN and GTAD, to use CUHK action class scores to get final localization result.
