### ISSUE TITLE
Has anyone reproduced the results of rgb model on THUMOS14 dataset?

### ISSUE THREAD

**Issue by dingli93** [TencentYoutuResearch/ActionDetection-AFSD#12]
I have trained the AFSD rgb model on THUMOS14 dataset as described in Implementation Details, and the experiment results are as follows:

0.3 | 0.4 | 0.5 | 0.6 | 0.7 | Avg.
57.7 | 52.5 | 44.6 | 35.1 | 23.4 | 42.6

However, the results are still about 1.0 lower than the value in the paper.
Could you offer help and figure out this problem?
Thanks a lot.

**Comment by linchuming** [comment]
@dingli93 , thanks for your attention. We found that the experiment results are unstable on different epochs for each training, so we trained our model two times and tested model parameters among 13 to 16 epochs to get the best performance. You can also try our experience to get the better results.

**Comment by huge123** [comment]
> I have trained the AFSD rgb model on THUMOS14 dataset as described in Implementation Details, and the experiment results are as follows:
> 
> 0.3 | 0.4 | 0.5 | 0.6 | 0.7 | Avg.
> 57.7 | 52.5 | 44.6 | 35.1 | 23.4 | 42.6
> 
> However, the results are still about 1.0 lower than the value in the paper.
> Could you offer help and figure out this problem?
> Thanks a lot.

I try to reproduce the experiment, but the results are very bad.  I wonder what data did you use to get such results,  the one that the author provided or you generated on your own?

**Comment by dingli-dean** [comment]
> > I have trained the AFSD rgb model on THUMOS14 dataset as described in Implementation Details, and the experiment results are as follows:
> > 0.3 | 0.4 | 0.5 | 0.6 | 0.7 | Avg.
> > 57.7 | 52.5 | 44.6 | 35.1 | 23.4 | 42.6
> > However, the results are still about 1.0 lower than the value in the paper.
> > Could you offer help and figure out this problem?
> > Thanks a lot.
> 
> I try to reproduce the experiment, but the results are very bad. I wonder what data did you use to get such results, the one that the author provided or you generated on your own?

Data provided by the author.
