### ISSUE TITLE
Missing default.yaml for video2npy.py

### ISSUE THREAD

**Issue by LUJUNYIhhh** [TencentYoutuResearch/ActionDetection-AFSD#14]
Hello! I'm new here and  I find that there lacks a file named default.yaml when I am trying to transform video to npy by myself. Expecting for your reply, thanks!
![image](https://user-images.githubusercontent.com/45595727/123895052-cdbaf880-d991-11eb-8962-ba86c0efceb4.png)

**Comment by linchuming** [comment]
Hi，@LUJUNYIhhh ，you can refer the updated README: `python3 video2npy.py configs/thumos14.yaml`.

**Comment by LUJUNYIhhh** [comment]
Got it! Thanks for reply!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TencentYoutuResearch/ActionDetection-AFSD"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月30日(星期三) 中午11:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [TencentYoutuResearch/ActionDetection-AFSD] Missing default.yaml for video2npy.py (#14)





 
Hi，@LUJUNYIhhh ，you can refer the updated README: python3 video2npy.py configs/thumos14.yaml.
