### ISSUE TITLE
CUDA_runtime error (98)

### ISSUE THREAD

**Issue by czhaneva** [TencentYoutuResearch/ActionDetection-AFSD#16]
非常感谢开源的工作！我在使用代码时会报错CUDA_runtime error (98)。
报错位置为：AFSD/prop_pooling/boundary_max_pooling_kernel.cu:110
我猜想应该是CUDA拓展出现了问题。
我的环境信息：
pytorch 1.4.0
torchvision 0.5.0
cuda: 10.0
另外：不知道有没有CPU版本的boundary_max_pooling_kernel呢？非常感谢！

**Comment by linchuming** [comment]
你好，目前这边暂时没有计划去写一份cpu的代码，用cpu训练也不实际。可以先检查一下你的环境，比如pytorch的cuda版本是不是10.0之类的。

**Comment by xiaojiangzhang** [comment]
> 非常感谢开源的工作！我在使用代码时会报错CUDA_runtime error (98)。
> 报错位置为：AFSD/prop_pooling/boundary_max_pooling_kernel.cu:110
> 我猜想应该是CUDA拓展出现了问题。
> 我的环境信息：
> pytorch 1.4.0
> torchvision 0.5.0
> cuda: 10.0
> 另外：不知道有没有CPU版本的boundary_max_pooling_kernel呢？非常感谢！

请问你的问题解决了吗，我现在遇到了同样的问题。

**Comment by czhaneva** [comment]
我的问题已经解决了，建议你按如下操作检查自己的环境
1. 查看torch.__version__  # 1.4.0
2. 查看torch.version.cuda  # 10.0 （我的环境）
3. 查看你服务器的CUDA拓展是否与（2）对应，可在/usr/local/<your cuda>查看是否一致
如果不一致，那么将很可能会报错，解决办法：
1. 安装对应的CUDA拓展
2. 或安装pytorch时，在官网选择与你服务器版本对应的cudatoolkit
3. 考虑非CUDA拓展版本的pooling操作

**Comment by yangjiangeyjg** [comment]
> 
> 
> 你好，目前这边暂时没有计划去写一份cpu的代码，用cpu训练也不实际。可以先检查一下你的环境，比如pytorch的cuda版本是不是10.0之类的。

请问CUDA必须是10.0吗

**Comment by linchuming** [comment]
@yangjiangeyjg 不是的，但是代码上在pytorch 1.4上跑的结果是对的，换成其他版本会有问题，而1.4版本官方对应的cuda是10.0，当然有其他对应CUDA的pytorch 1.4也可以。
