### ISSUE TITLE
请问i3d预训练模型flow_imagenet.pt和rgb_imagenet.pt模型来源于哪里？

### ISSUE THREAD

**Issue by yangmin666** [TencentYoutuResearch/ActionDetection-AFSD#21]
是自己训练的吗？预训练时模型的图片输入维度是多少

**Comment by linchuming** [comment]
Hi @yangmin666 , we did not train the I3D network from scratch and use the pretrained models from https://github.com/piergiaj/pytorch-i3d, which are trained on Kinetics 400 dataset.
