### ISSUE TITLE
Data download links

### ISSUE THREAD

**Issue by shubhamagarwal92** [TencentYoutuResearch/ActionDetection-AFSD#23]
Hi, 

Could you please provide the download links for the `THUMOS14 RGB data` numpy files instead of the [Weiyun](https://github.com/TencentYoutuResearch/ActionDetection-AFSD#data-preparation) link provided here? I am not able to access the link `https://share.weiyun.com/bP62lmHj`. 

Something either on GDrive or a link with `wget` access could work. 

Thank you for your help!

**Comment by shubhamagarwal92** [comment]
Also for the Weiyun links for the [Activity net dataset](https://github.com/TencentYoutuResearch/ActionDetection-AFSD/blob/master/AFSD/anet/README.md)

**Comment by shubhamagarwal92** [comment]
Hi @linchuming any updates on this? Thanks!

**Comment by linchuming** [comment]
@shubhamagarwal92 
Because of the limitation of Google Drive (only 15GB space), I can not provide GDrive link of the RGB npy data. You can download the original videos and generate the RGB npy data following the README.

**Comment by shubhamagarwal92** [comment]
No worries! Thanks for replying. 
If you decide to host the Activity net dataset on any other open-sourced cloud service, please let me know. 
Closing this now.
