### ISSUE TITLE
support for multi-GPU

### ISSUE THREAD

**Issue by Kaeless** [TencentYoutuResearch/ActionDetection-AFSD#27]
我在复现代码的过程当中发现这个repo不支持多卡，在这里把我个人的解决方法写到这里把，希望作者可以更新一下多卡版本
采用4块V100进行训练，修改的地方：
train.py->def forward_one_epoch(net, clips, targets, scores=None, training=True, ssl=True):
 ``` python
   if training:
        if ssl:
            tar = targets[0]
            pro = torch.stack([tar,tar,tar,tar],dim=0)
            output_dict = net(clips, proposals=pro, ssl=ssl)
        else:
            output_dict = net(clips, ssl=False)
            output_dict['priors'] = output_dict['priors'][0:126:]
 ```

**Comment by linchuming** [comment]
@Kaeless , thanks for your suggestion. We have updated our AFSD code to support training with multiple GPUs.
