### ISSUE TITLE
CUDA error for setup.py 

### ISSUE THREAD

**Issue by shadowclouds** [TencentYoutuResearch/ActionDetection-AFSD#28]

**Comment by shadowclouds** [comment]
When I run setup.py.  I meet error ValueError: Unknown CUDA arch (8.6) or GPU not supported.
my environment is : CUDA 11.2  torch 1.4.0  GPU machine: A6000
I guess this error occurs for the high version of CUDA (A6000 needs the CUDA version higher than 11.0)
Do you have any advise for this problem?
thanks

**Comment by linchuming** [comment]
You can try to update the pytorch and support the cuda 11.2, but the results may be different because we do not test our code in other pytorch version.
