### ISSUE TITLE
ActivityNet files?

### ISSUE THREAD

**Issue by wjn922** [TencentYoutuResearch/ActionDetection-AFSD#3]
Hi @linchuming ,

     Thanks for your sharing code. I wonder whether you can also upload the npy files of ActivityNet dataset?
     Thank you.

**Comment by linchuming** [comment]
@wjn922, due to the large npy data, we could not upload the npy files. But, we provide some intermediate files on Weiyun, and you can use those files to generate the input npy data .

**Comment by wjn922** [comment]
Hi @linchuming,

Thanks for your sharing. But I find there are many files in the two provided 7z files are corrupted. Could you please check these two files again? Thank you.

**Comment by linchuming** [comment]
@wjn922, we use 7za (p7zip) to pack files. Could you try use the same tool to unpack?

**Comment by wjn922** [comment]
This works. Thanks very much.
