### ISSUE TITLE
Calculate accuracy for each class

### ISSUE THREAD

**Issue by Powercoder64** [TencentYoutuResearch/ActionDetection-AFSD#33]
Hello,
Thanks for your great work, Is there any code/tool to calculate the accuracy/mAP for each individual class?

**Comment by linchuming** [comment]
@Powercoder64 I consider the ap result  https://github.com/TencentYoutuResearch/ActionDetection-AFSD/blob/ed86a0df91e58baa7d78c796ed29cff82b1f3fa6/AFSD/thumos14/eval.py#L14 is your need.

**Comment by Powercoder64** [comment]
Thanks for your response.
