### ISSUE TITLE
confidence score for long videos

### ISSUE THREAD

**Issue by Powercoder64** [TencentYoutuResearch/ActionDetection-AFSD#34]
Hi,
I checked your codes on very long videos and I got a lot of false positives. What will be the best values for conf_thresh and top_k?

**Comment by linchuming** [comment]
@Powercoder64 , we tried to raise the conf_thresh and reduce the top_k, but the mAP will be degraded. You can attempt to use other conf_thresh or other post-processing to meet your purpose.

**Comment by Powercoder64** [comment]
> @Powercoder64 , we tried to raise the conf_thresh and reduce the top_k, but the mAP will be degraded. You can attempt to use other conf_thresh or other post-processing to meet your purpose.

Thanks. So, what does the  top_k mean exactly? Since its value is 5000, I hesitate that it should be the top highest scores since there are not 5000 classes in the dataset.

**Comment by linchuming** [comment]
@Powercoder64 , the target of this task is to improve mAP, so we use the larger top_k will increase the recall value and get higher mAP value.
