### ISSUE TITLE
Actual number of classes and class indice

### ISSUE THREAD

**Issue by Powercoder64** [TencentYoutuResearch/ActionDetection-AFSD#35]
Hello,

Thank you for your great work,

I found out that the number of classes in the config file for thumos14 dataset is the actual number of classes + 1.  Here, thumos14 dataset has 20 classes while the config file is set to 21. I also tried it in my costume dataset, and I found out that the number of classes in the config file should be set to the number of actual classes + 1.  Otherwise, it gives an error. So, what is that extra class? How can I find the original class indices after the action detection is complete?

**Comment by linchuming** [comment]
@Powercoder64 20 action classes + 1 background class (it means no action happens). Generally, class indices will be  designed manually in training process.

**Comment by Powercoder64** [comment]
Thank you so much for your time. Do, for the  thumos14 dataset, background class is the first class index or the last index?

**Comment by Powercoder64** [comment]
> @Powercoder64 20 action classes + 1 background class (it means no action happens). Generally, class indices will be designed manually in training process.

Thank you so much for your time. So, for the  thumos14 dataset, background class is the first class index or the last index?

**Comment by Powercoder64** [comment]
I actually found it out. Thanks.
