### ISSUE TITLE
Usage of UntrimmedNet Result used during post-processing of ActivityNet

### ISSUE THREAD

**Issue by anonyn498** [TencentYoutuResearch/ActionDetection-AFSD#4]
Hi, 

Congrats for your awesome work. 

I just want to know why is the Untrimmednet result used during post process ? After reading your paper, it is evident that this work is a localization network ( classification + proposals ) , so why is the UntrimmedNet coming here ? Isnt this network supposed to give you action classification as well ? 

Thanks in advance

**Comment by linchuming** [comment]
We follow the previous work, such as BMN and GTAD, which also use the untrimmednet video classification result, because most videos of ActivityNet contain only one action class. We had attempted to predict class score in our framework but it will drop a lot of performance.

**Comment by anonyn498** [comment]
Thanks for your response. Yes, that is a known problem but it is not written in the paper that you have used UntrimmedNet. 
My follow-up question to this is BMN and GTAD used UntrimmedNet because it is a proposal only architecture i.e no branch to predict the action class, so it is bound to use a separate network for this. But your network has a separate branch to predict the class that's why my confusion arises
