### ISSUE TITLE
about thumos14

### ISSUE THREAD

**Issue by menghuaa** [TencentYoutuResearch/ActionDetection-AFSD#42]
Hello, do you remove the background data provided by the thumos 14 dataset during training and testing?

**Comment by linchuming** [comment]
THUMOS14 data will be split into clips using sliding window with overlap. In training,  background clips without any foreground will be removed. In testing, all clips should be considered and reserved.

**Comment by menghuaa** [comment]
> THUMOS14 数据将使用重叠的滑动窗口分割成片段。在训练中，没有任何前景的背景剪辑将被删除。在测试中，应考虑并保留所有剪辑。
I  mean thumos14 annotations file：val_Annotation_ours.csv、test_Annotation_ours.csv and thumos_gt.json.I see that GTAD don‘t remove them.
