### ISSUE TITLE
Query regarding the Input Video processing

### ISSUE THREAD

**Issue by sauradip** [TencentYoutuResearch/ActionDetection-AFSD#47]
Hi , i observed that the video for ANet dataset is trimmed off to have 768 frames , most likely to fit GPU. But my question , when feeding  the data to I3D backbone , is it sent as ( batch, channel = 3 , temporal = 768 , height, width ) dimension ? or you break it up into windows of 16 and repeatedly fit in the data ?

**Comment by linchuming** [comment]
@sauradip , hi,
the input size of the I3D backbone is (batch, 3, 768, 96, 96), due to the tradeoff the efficiency and effect. The I3D backbone will be funetuning during the training process.

**Comment by sauradip** [comment]
Thanks for the response
