### ISSUE TITLE
Architecture of Pyramid Feature Network

### ISSUE THREAD

**Issue by vhvkhoa** [TencentYoutuResearch/ActionDetection-AFSD#5]
Hello,

Firstly, I'd like to thank you much for publishing the code and congratulations about the CVPR'21 paper.

I would like to have an overview of the architecture of pyramid feature module in your pipeline, it is noted to be shared in supplementary, but unfortunately I cannot get access to it.
Could you please share the pdf file of supplementary?

**Comment by linchuming** [comment]
Hi, @vhvkhoa , the supplementary has been added to this repo.
