### ISSUE TITLE
Could you explain the the meaning of function augment_() in AFSD/common/thumos_dataset.py?

### ISSUE THREAD

**Issue by yangmin666** [TencentYoutuResearch/ActionDetection-AFSD#6]
I can not understand your operation in that function augment_(). What is the meaning of  new_input and new_annos?I am completely confused.Thank you!

**Comment by loadder** [comment]
Hi yangming,
this function is used to implement the boundary contrastive learning in our paper. We first randomly sample one suitable action (L194) and background snippet (L204). Then the background is inserted at a random position in the action (L212-L225). Then such a process is repeated several times in function augment() to generate more pairs for BCL.
Hope this can help you.
