### ISSUE TITLE
Why we use the function ScaleExp() in BDNet.py?

### ISSUE THREAD

**Issue by yangmin666** [TencentYoutuResearch/ActionDetection-AFSD#7]
I checked the code carefully according to the formula(1 and 3) in the paper. I could not understand why we use ScaleExp()?In the code,"l_segment = new_priors - segments[:, :, :1]".Do we divide the both parts of the formula 3 by 2^l？Thank you!!

**Comment by linchuming** [comment]
We refer some details of anchor-free designation from object detection methods, such as FCOS. ScaleExp is also used in FCOS and increases the performance. If you are interesting in anchor-free, you can read some classical paper, such as FCOS and CenterNet.
